### ISSUE TITLE
About Net input

### ISSUE THREAD

**Issue by A-cloud-bit** [cscvlab/UODFs#1]
This is a very good job. i 'm sorry. As far as I know, implicit representation requires conditions such as images, point clouds, voxels, etc. However, after reading the paper, I have not determined what the input of the network is? Why are there only a few points

**Comment by hammer-cai** [comment]
This category of implicit 3D representation methods encodes the shape by network parameters. Thus there is no other input for network, except the tested 3d points. You can refer to some previous works to understand its mechaniam, such as DeepSDF and NGLOD.

The works you mentioned are actually half-implicit or called hybrid implicit representation, in my opinion.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/06/2024 15:31 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [cscvlab/UODFs] About Net input (Issue #1) |

This is a very good job. i 'm sorry. As far as I know, implicit representation requires conditions such as images, point clouds, voxels, etc. However, after reading the paper, I have not determined what the input of the network is? Why are there only a few points

**Comment by hammer-cai** [comment]
The example of nglod is not proper, as it is actually one hybrid representation combining voxel and neural implicit representation (SDF).



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/06/2024 15:31 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [cscvlab/UODFs] About Net input (Issue #1) |

This is a very good job. i 'm sorry. As far as I know, implicit representation requires conditions such as images, point clouds, voxels, etc. However, after reading the paper, I have not determined what the input of the network is? Why are there only a few points

**Comment by A-cloud-bit** [comment]
Understood, thank you very much for your answer
