### ISSUE TITLE
train/test/val split

### ISSUE THREAD

**Issue by rsy6318** [cscvlab/UODFs#2]
Hi, I wonder what is the train/test/val split in your experiment? In the code provided, it seems that the model overfits shapes one by one? Looking forward your reply!

**Comment by hammer-cai** [comment]
Yes. Currently, UODFs overfit one model and save it in its mlp parameters, like NeRF's and Nglod's geometric representation. Its advantages reflects in its accuracy for reconstructing models at any resolution. For example, grid edge points can be accurately predicted at resolution higher than 256^3.



---- Replied Message ----
| From | Siyu ***@***.***> |
| Date | 09/13/2024 10:31 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [cscvlab/UODFs] train/test/val split (Issue #2) |

Hi, I wonder what is the train/test/val split in your experiment? In the code provided, it seems that the model overfits shapes one by one? Looking forward your reply!
