### ISSUE TITLE
model

### ISSUE THREAD

**Issue by thousanddrowned** [cscvlab/UODFs#3]
good works. could you provide the checkpoints shown in your demo?

**Comment by wl4318** [comment]
We'd be happy to provide some pre-trained models, along with the reconstructed point clouds and meshes. However, the combined size is quite large. We can offer 2-3 models. Could you let us know which models you’d like to see results for?

**Comment by thousanddrowned** [comment]
@wl4318

**Comment by thousanddrowned** [comment]
@wl4318 Thanks for your prompt reply. I need the models for some complex and large point cloud data(like Stanford 3D Scanning or other data mentioned in your paper), again, thank you.

**Comment by wl4318** [comment]
@thousanddrowned Thank you for your message. The compressed package includes the original .obj files for models such as stanford_dragon, shark_new, and waving cat, along with pre-trained models, reconstructed point cloud results, and mesh results. 

Our experiments were conducted within the space of [-1,1] at a resolution of 256x256x256, so the number of points in the point clouds is not excessively large. 

https://drive.google.com/file/d/1oMRqTB1O9CafD_hdSAqOW6HeOwrOsZ_M/view?usp=drive_link
