### ISSUE TITLE
point cloud data or mesh

### ISSUE THREAD

**Issue by thousanddrowned** [cscvlab/UODFs#5]
Is the workflow to sample point clouds in three orthogonal directions from an existing mesh model and then reconstruct the mesh? Is it possible to directly reconstruct a mesh from point cloud data?

**Comment by hammer-cai** [comment]
Our method aims to accurate neural implicit representation of models. Specifically, it utilizes the intersection points between the edges of voxel grids and surface mesh to train three distance fields along orthogonal directions, and predict these intersection points in inference, followed by  meshing them (if mesh is required). The advantages reflects in the accuracy at multiple resolutions, the unified manipulation for watertight/non- objects, etc.  

Regarding your question,  to my knowledge, there are rarely methods directly reconstructing or generating a mesh from implicit fields (marching cube simultaneous reconstruct intersection points and accomplish meshing).

**Comment by hammer-cai** [comment]
There are indeed some works to generate meshes directly from point clouds. To our knowledge, points, image, or text is the input of their large networks, and 3D triangles as ordered tokens are output. Maybe you could explore these works in deep.
